Add check to fail the step if tests requiring live MongoDB are skipped

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -78,12 +78,16 @@ jobs:
         # mongodb-version: "4.03"
     - name: Test connection to MongoDB instance
       if: matrix.mongodb_server
+      env:
+        _tests_that_should_not_be_skipped: db_api
+        _pytest_output_to_inspect: .pytest-edb-mongodb.log
       run: |
         # load EDB
         edb load -b
-        # TODO it would be better to use a command that fails if tests are skipped
-        pytest -k 'db_api' -sv
-        pytest -k 'edb' -sv
+        # run subset of tests that should not be skipped if the MongoDB instance is accessible to the EDB
+        pytest -k "$_tests_that_should_not_be_skipped" --verbose --capture=tee-sys | tee "$_pytest_output_to_inspect"
+        # "reverse grep": the overall command fails unless no match was found (exit code 1)
+        grep "SKIPPED" "$_pytest_output_to_inspect" ; test $? -eq 1
     - name: Add coverage report options
       if: matrix.cov_report
       run: echo 'PYTEST_ADDOPTS="--cov-report=xml"' >> $GITHUB_ENV
